# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#


version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  shopizer-ci:
    docker:
      - image: shopizerecomm/ci:latest
        auth:
          username: shopizerecomm
          password: $DOCKERHUB_PASSWORD

working_directory: /tmp


# Define the jobs we want to run for this project
jobs:
  build:
    executor: shopizer-ci
    steps:
      - checkout
      - run: echo "shopizer build and test (1)"
      - run:
          name: Run shell script
          command: |
            set -x
            /home/shopizer/tools/shopizer.sh tests
      - persist_to_workspace:
          root: .
          paths:
            - sm-shop/*
      #- run:
      #    name: Install Docker client
      #    command: apk add docker-cli
      #- run: |
      #    ls -al
      #    cd sm-shop
      #    docker build . -t shopizerecomm/shopizer:latest
      #    docker build . -t shopizerecomm/shopizer:latest
  deploy:
    machine: true
    steps:
      - attach_workspace:
          at: .
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: |
          ls -al
      - run: |
          docker login -u shopizerecomm -p $DOCKERHUB_PASSWORD
      - run: |
          (cd sm-shop && docker build . -t shopizerecomm/shopizer:latest)
      - run: |
          docker push shopizerecomm/shopizer:latest

      #- run: |
      #    docker login -u shopizerecomm  -p $DOCKERHUB_PASSWORD  | ls -al | echo "build docker" | cd sm-shop | ls -al | docker build . -t shopizerecomm/shopizer:latest

      # deploy the image
      #- run: docker push shopizerecomm/shopizer:latest

# Orchestrate our job run sequence
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build


      #jobs:
      #  build:
      #    steps:
      #      - checkout
      #      - run: echo "this is the build job"
      #  test:
      #executor: shopizer-ci
      #    steps:
      #      - checkout
      #      - run: echo "this is the test job"
      #- run: shopizer tests



#workflows:
#  build_and_test:
#    jobs:
#      - build
#      - test:
#          requires:
#            - build